# Generated by Django 5.2.7 on 2025-10-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('restart_command', models.BooleanField(default=False, help_text="If is enabled, run the command when calls the project's restart")),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'db_table': 'command',
            },
        ),
    ]
