# Generated by Django 5.2.7 on 2025-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='dummy', max_length=64),
            preserve_default=False,
        ),
    ]
