# Generated by Django 5.2.7 on 2025-10-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_command_name'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='project.project'),
        ),
    ]
