# Generated by Django 5.2.7 on 2025-10-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_alter_command_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='cwd',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
