# Generated by Django 5.2.7 on 2025-10-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('versao_anterior', models.CharField(max_length=32)),
                ('versao_atualizacao', models.CharField(max_length=32)),
                ('branch', models.CharField(blank=True, max_length=128, null=True)),
                ('hash_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('S', 'Sucesso'), ('E', 'Erro')], max_length=1)),
            ],
            options={
                'verbose_name': 'Log de Atualização',
                'verbose_name_plural': 'Logs de Atualização',
                'db_table': 'log_atualizacao',
                'ordering': ['-data'],
            },
        ),
    ]
