# Generated by Django 5.2.7 on 2025-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('versao_anterior', models.CharField(max_length=32)),
                ('versao_atualizacao', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('S', 'Sucesso'), ('E', 'Erro')], max_length=1)),
            ],
            options={
                'db_table': 'atualizacoes',
                'ordering': ['-data'],
            },
        ),
    ]
