# Generated by Django 5.2.7 on 2025-10-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'db_table': 'command',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=128)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('remote', models.CharField(default='origin', max_length=64)),
                ('branch_trunc', models.CharField(default='main', max_length=64)),
                ('branch_dev', models.CharField(blank=True, max_length=64, null=True)),
                ('branch_homolog', models.CharField(blank=True, max_length=64, null=True)),
                ('branch_prod', models.CharField(blank=True, max_length=64, null=True)),
                ('commands', models.ManyToManyField(blank=True, related_name='aplicacoes', to='project.command')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'project',
                'ordering': ['name'],
            },
        ),
    ]
