# Generated by Django 5.2.7 on 2025-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_update',
            field=models.BooleanField(default=True, help_text='If enabled, the project will be automatically updated.'),
        ),
    ]
