# Generated by Django 5.2.7 on 2025-10-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_auto_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='branch_dev',
            new_name='development_branch',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='branch_homolog',
            new_name='homologation_branch',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='branch_prod',
            new_name='production_branch',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='branch_trunc',
            new_name='trunk_branch',
        ),
    ]
