# Generated by Django 5.2.7 on 2025-10-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_branch_dev_project_development_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='development_branch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='homologation_branch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='production_branch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='trunk_branch',
        ),
    ]
