# Generated by Django 5.2.7 on 2025-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500)),
                ('ip', models.GenericIPAddressField()),
                ('porta', models.IntegerField()),
                ('usa_tls', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['id'],
                'unique_together': {('ip', 'porta')},
            },
        ),
    ]
