# Generated by Django 5.2.7 on 2025-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before_version', models.CharField(max_length=32)),
                ('updated_version', models.CharField(max_length=32)),
                ('branch', models.CharField(blank=True, max_length=128, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('S', 'Sucesso'), ('E', 'Erro')], max_length=1)),
            ],
            options={
                'verbose_name': 'Update Log',
                'verbose_name_plural': 'Update Logs',
                'db_table': 'update_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
