# Generated by Django 5.2.7 on 2025-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'db_table': 'comando',
            },
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('caminho', models.CharField(max_length=128)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('remote', models.CharField(default='origin', max_length=64)),
                ('branch_trunc', models.CharField(default='main', max_length=64)),
                ('branch_dev', models.CharField(blank=True, max_length=64, null=True)),
                ('branch_homolog', models.CharField(blank=True, max_length=64, null=True)),
                ('branch_prod', models.CharField(blank=True, max_length=64, null=True)),
                ('comandos', models.ManyToManyField(blank=True, related_name='aplicacoes', to='aplicacao.comando')),
            ],
            options={
                'verbose_name': 'Aplicação',
                'verbose_name_plural': 'Aplicações',
                'db_table': 'aplicacao',
                'ordering': ['nome'],
            },
        ),
    ]
