# Generated by Django 5.2.7 on 2025-10-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
    ]
